swagger: '2.0'
info:
  version: 0.0.1
  title: city
  description: pre-alpha api documentation
schemes:
  - http
host: localhost:8080
basePath: /api
securityDefinitions:
  JWT:
    description: ""
    type: "apiKey"
    name: "Authorization"
    in: "header"
paths:
  /businesses:
    get:
      tags: 
      - "BusinessSide"
      summary: Get all businesses
      description: Fetches all businesses owned by the owner and not owned by anyone.
      parameters: 
      - name: "owner"
        in: "header"
        required: true
        type: "string"
      responses:
        200:
          description: OK
          schema:
            type: "array"
            items:
              $ref: '#/definitions/BusinessObj'
              
  /businesses/{businessId}:
    patch:
      tags: 
        - "BusinessSide"
      summary: CHANGEME
      description: CHANGEME
      security: 
      - JWT: []
      parameters:
      - name: "businessId"
        in: "path"
        required: true
        type: "string"
      - name: "business"
        in: "body"
        schema:
          properties:
            business:
              type: "object"
              $ref: '#/definitions/BusinessObj'
      responses:
        200:
          description: OK
          
  /businesses/claim/{businessId}:
    patch:
      tags: 
      - "BusinessSide"
      summary: Claims the business.
      description: Claims the business using the business id of the owner.
      security: 
      - JWT: []
      parameters: 
      - name: "owner"
        in: "header"
        required: true
        type: "string"
      - name: "businessId"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: OK
          schema:
            properties:
              code:
                type: "number"
              message:
                type: "string"          
          
  /businesses/declaim/{businessId}:
    patch:
      tags: 
      - "BusinessSide"
      summary: Claims the business.
      description: Claims the business using the business id of the owner.
      security: 
      - JWT: []
      parameters: 
      - name: "owner"
        in: "header"
        required: true
        type: "string"
      - name: "businessId"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: OK
          schema:
            properties:
              code:
                type: "number"
              message:
                type: "string"


    
  /getAllZones:
    post:
      tags: 
        - "Client Mobile"
      summary: Get all current available beacons.
      description: Fetches all registered beacons from the database.
      responses:
        '200':
          description: OK
          schema:
            type: "object"
            properties:
              code:
                type: number
              message:
                type: "string"
              data:
                type: "array"
                items:
                    $ref: '#/definitions/Beacon'       
          
  /getOffersForBeacon:
    post:
      tags: 
        - "Client Mobile"
      summary: Receives all offers for beacon
      description: Receives all offers for beacon
      parameters:
        - name: "body"
          in: body
          required: true
          schema:
            properties:
              uuId:
                type: "string"
      responses:
        '200':
          description: OK
          schema:
            type: "object"
            properties:
              code:
                type: number
              message:
                type: "string"
              data:
                type: "array"
                items:
                  $ref: '#/definitions/Offer'
              business:
                type: "object"
                $ref: '#/definitions/BusinessObj'
    

definitions:
  TargetAudience:
    type: "object"
    properties:
      minAge:
        type: "number"
      maxAge:
        type: "number"
      gender:
        type: "string"
  
  Offer:
    type: "object"
    properties:
      title:
        type: "string"
      comment:
        type: "string"
      description:
        type: "string"
      targetAudience:
        type: "object"
        $ref: "#/definitions/TargetAudience"
      expiration:
        type: "string"
        format: "date"
        
  Beacon:
    type: "object"
    properties:
      attachmentKey: 
        type: "string"
      attachmentValue:
        type: "string"
      uuId:
        type: "string"
      
      
  BusinessObj:
    type: "object"
    properties:
      _id:
        type: "string"
      name:
        type: "string"
      address:
        type: "string"
      owner:
        description: "Owner id"
        type: "string"
      beacon:
        type: "object"
        $ref: '#/definitions/Beacon'
      offers:
        type: "array"
        items:
          $ref: '#/definitions/Offer'
      approved:
        type: "boolean"
        
  Customer:
    type: "object"
    properties:
      deviceId:
        type: "string"
      gender:
        type: "string"
      dob:
        description: "Date of birth"
        type: "string"
      
  Owner:
    type: "object"
    properties:
      username:
        type: "string"
      email:
        type: "string"
      password:
        type: "string"
        format: "password"
      businesses:
        type: "array"
        items:
          $ref: '#/definitions/BusinessObj'
          
  Visit:
    type: "object"
    properties:
      business:
        type: "object"
        $ref: '#/definitions/BusinessObj'
      customer:
        type: "object"
        $ref: '#/definitions/Customer'
  
  